- name: # TASK 1
  hosts: servers
  become: yes
  
  tasks:
   - name: # Копируем файл с конфигурацией для сервиса
     ansible.builtin.copy: 
      src: ./files/watchlog
      dest: /etc/default/watchlog
   - name: # Копируем скрипт
     ansible.builtin.copy:
      src: ./files/watchlog.sh
      dest: /opt/watchlog.sh
      mode: '+x'
   - name: # Копируем юнит для сервиса
     ansible.builtin.copy: 
      src: ./files/watchlog.service
      dest: /etc/systemd/system/watchlog.service
   - name: # Копируем юнит для таймера
     ansible.builtin.copy:    
      src: ./files/watchlog.timer
      dest: /etc/systemd/system/watchlog.timer
   - name: Запуск watchlog.timer
     ansible.builtin.systemd:
        name: watchlog.timer
        state: started
