
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64" # Используем образ Ubuntu для виртуальной машины
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024" # Указываем размер памяти для виртуальной машины 
    vb.cpus = 2  # Выделяем необходимое количество процессоров для виртуальной машины
  end

  ##### Обновление ядра ##### 
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update # Обновляем пакеты
    sudo apt-get install -y linux-image-generic  # Устанавливаем последнюю версию ядра
    sudo reboot # Для применения нового ядра перезагружаем виртуальную машину 
  SHELL
end