
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64" # Используем образ Ubuntu для виртуальной машины
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024" # Указываем размер памяти для виртуальной машины 
    vb.cpus = 2  # Выделяем необходимое количество процессоров для виртуальной машины
  end

  ##### Обновление ядра ##### 
  config.vm.provision "shell", inline: <<-SHELL
    ### Скачиваем пакеты для обновления
    wget https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.19/amd64/linux-headers-5.19.0-051900-generic_5.19.0-051900.202207312230_amd64.deb
    wget https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.19/amd64/linux-image-unsigned-5.19.0-051900-generic_5.19.0-051900.202207312230_amd64.deb
    wget https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.19/amd64/linux-modules-5.19.0-051900-generic_5.19.0-051900.202207312230_amd64.deb  
    ### Устанавливаем скачанные пакеты
    sudo dpkg -i *.deb
    ### Обновляем загрузчик 
    sudo update-grub
    ### Перезагружаемся
    sudo reboot
  SHELL
end